kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-image
parameters:
  - name: NAME
    required: true
  - name: SOURCE
    required: true
  - name: BUILD_VERSION
    required: true
    value: "latest"
  - name: STAGE
    required: true
    value: "dev"
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        stage: ${STAGE}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${BUILD_VERSION}
      source:
        type: "Dockerfile"
        dockerfile: |-
          ${SOURCE}
        contextDir: /
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
