kind: Template
apiVersion: v1
metadata:
  name: deploytemplate-webapp
parameters:
  - name: APP_NAME
    required: true
  - name: IMAGE
    required: true
  - name: STAGE
    required: true
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      generation: 1
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
        deploymentconfig:  ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentconfig:  ${APP_NAME}
            stage: ${STAGE}
        spec:
          containers:
          - env:
            - name: APP_NAME
              value: ${APP_NAME}
            - name: STAGE
              value: ${STAGE}
            image: ${IMAGE}
            imagePullPolicy: Always
            name: ${APP_NAME}
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 5010
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            livenessProbe:
              failureThreshold: 15
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 15
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 5
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /opt/${APP_NAME}/config
                name: ${APP_NAME}-config
                readOnly: true
              - mountPath: /opt/${APP_NAME}/env
                name: ${APP_NAME}-env
                readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ${APP_NAME}-config
              configMap:
                defaultMode: 420
                name: ${APP_NAME}-${STAGE}-config
            - name: ${APP_NAME}-env
              secret:
                defaultMode: 420
                secretName: ${APP_NAME}-${STAGE}-env
      test: false
 

