- name: create virtual host file
  when: ansible_os_family == "Debian"
  template: src=virtualhost.conf dest={{ apache_root }}/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  when: ansible_os_family == "Debian"
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
    - restart apache2

- name: create virtual host file
  when: ansible_os_family == "RedHat"
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/{{ domain }}.conf
  notify:
    - restart httpd