---

- name: Create archive directory
  file:
    path: "{{ archive_dir }}"
    state: directory
    mode: 0755

- name: Install libselinux-python
  # Required for centos6.
  yum: name=libselinux-python state=present

- name: Install redis build deps 
  yum: name={{ item }} state=present
  with_items:
  - make
  - gcc
  - wget

- name: Download redis source code
  get_url:
    url: "{{ redis_download_url }}"
    dest: "{{ archive_dir }}/redis-{{ redis_version }}.tar.gz"

- name: Extract redis source code
  unarchive:
    src: "{{ archive_dir }}/redis-{{ redis_version }}.tar.gz"
    dest: "{{ inera_root }}"
    remote_src: yes
    creates: "{{ inera_root }}/redis-{{ redis_version }}"

- name: Compile redis
  shell: make chdir={{ inera_root }}/redis-{{ redis_version }} creates={{ archive_dir }}/redis-{{ redis_version }}/src/redis-server

- name: Create symlinks in /usr/local/bin to redis home
  file: 
    state: link
    src: "{{ inera_root }}/redis-{{ redis_version }}/src/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  with_items:
  - redis-cli
  - redis-server
  - redis-benchmark

- name: Create redis user
  user: name=redis

- name: Create redis working folder
  file: path=/var/redis/{{ redis_port }} state=directory recurse=yes owner=redis group=redis

- name: Create redis config(s) folder
  file: path=/etc/redis state=directory owner=redis group=redis

- name: Create main redis config for port {{ redis_port }}
  template:
    src: "redis.conf.j2"
    dest: "/etc/redis/{{ redis_port }}.conf"
    owner: redis
    group: redis
    mode: 0644

- name: Create init.d script
  template:
    src: "redis_init_script.j2"
    dest: "/etc/init.d/redis_{{ redis_port }}"
    owner: root
    group: root
    mode: 0755

- name: Start redis server
  service:
    name: redis_{{ redis_port }}
    state: started
    enabled: yes
    pattern: "~/usr/local/bin/redis-server (.)+:{{ redis_port }}"

