---

- name: Install gcc-c++ from yum
  yum:
    name: gcc-c++
    state: present

- name: Install openssl-devel from yum
  yum:
    name: openssl-devel
    state: present

- name: Checkout git-crypt from github
  git:
    repo: https://github.com/AGWA/git-crypt.git
    dest: "{{ inera_root }}/git-crypt"

- name: Build git-crypt
  make: 
    chdir: "{{ inera_root }}/git-crypt"

- name: Copy git-crypt to /usr/local/bin
  copy:
    src: "{{ inera_root }}/git-crypt/git-crypt"
    dest: "/usr/local/bin"
    mode: 0755
    remote_src: True
