---

- name: Install gcc-c++ from yum
  yum: name=gcc-c++ state=present

- name: Install openssl-devel from yum
  yum: name=openssl-devel state=present

- name: Checkout git-crypt from github
  git: repo=https://github.com/AGWA/git-crypt.git dest="{{ inera_root }}/git-crypt"

- name: Build git-crypt
  command: make
  args:
    chdir: "{{ inera_root }}/git-crypt"
    creates: "{{ inera_root }}/git-crypt/git-crypt"

- name: Copy git-crypt to /usr/local/bin
  command: cp {{ inera_root }}/git-crypt/git-crypt /usr/local/bin
  args:
    creates: /usr/local/bin/git-crypt
