---

- name: Create archive directory
  file:
    path: "{{ archive_dir }}"
    state: directory
    mode: 0755

- name: Download activemq
  get_url:
    url: "{{ activemq_download_url }}"
    dest: "{{ archive_dir }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"

- name: Extract activemq
  unarchive:
    src: "{{ archive_dir }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"
    dest: "{{ inera_root }}"
    remote_src: yes
    creates: "{{ inera_root }}/apache-activemq-{{ activemq_version }}"

- name: Create symlink to actimemq home
  file:
    state: link
    src: "{{ inera_root }}/apache-activemq-{{ activemq_version }}"
    path: "{{ activemq_home }}"
    mode: 0755

- name: Make script executable
  file:
    path: "{{ activemq_home }}/bin/activemq"
    mode: 0755

- name: Make service script executable
  file:
    path: "{{ activemq_home }}/bin/linux-x86-64/activemq"
    mode: 0755

- name: Make service link
  file:
    state: link
    src: "{{ activemq_home }}/bin/linux-x86-64/activemq"
    path: /etc/init.d/activemq
    mode: 0755

- name: Start ActiveMQ
  service:
    name: activemq
    state: started
    enabled: yes
    pattern: activemq
