---
- name: install activemq from yum
  when: ansible_os_family == "RedHat"
  yum: name=activemq state=present

- name: install activemq from apt
  when: ansible_os_family == "Debian"
  apt: name=activemq state=present

- name: enable activemq
  when: ansible_os_family == "Debian"
  file: src=/etc/activemq/instances-available/main dest=/etc/activemq/instances-enabled/main state=link
  
- name: Enable ActiveMQ
  service: name=activemq enabled=yes

- name: Start ActiveMQ
  service: name=activemq state=started pattern=activemq
