apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: activemq
    environment: test
  name: activemq
spec:
  replicas: 1
  selector:
    app: activemq
    deploymentconfig: activemq
  template:
    metadata:
      labels:
        app: activemq
        deploymentconfig: activemq
        environment: test
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_USERNAME
          value: admin
        - name: ACTIVEMQ_PASSWORD
          value: admin
        image: eriklupander/activemq:latest
        imagePullPolicy: IfNotPresent
        name: activemq
        ports:
        - containerPort: 1883
          protocol: TCP
        - containerPort: 5672
          protocol: TCP
        - containerPort: 8161
          protocol: TCP
        - containerPort: 61613
          protocol: TCP
        - containerPort: 61614
          protocol: TCP
        - containerPort: 61616
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /opt/inera/activemq-konfiguration
            name: volume-activemq-test-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: activemq-test
          name: volume-activemq-test-configmap
  test: false
