apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: rehabstod
    template: application-template-sample-pipeline
  name: rehabstod
  namespace: intygstjanster-test
spec:
  lookupPolicy:
    local: false
