---

- name: Ensure apache packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ apache_packages }}"
  register: apache_install_packages

- name: Check whether certificates defined in vhosts exist.
  stat:
    path: "{{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Create base vhost config and load balancing.
  template:
    src: "vhosts.conf.j2"
    dest: "/etc/httpd/conf.d/{{ domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Fix ssl.conf _default_ vhost
  lineinfile:
    dest: "/etc/httpd/conf.d/ssl.conf"
    regexp: "<VirtualHost .*:443>"
    line: "<VirtualHost 127.0.0.1:443>"

- name: Turn on NameVirtualHost for http and https
  lineinfile:
    dest: "{{ item.filename }}"
    regexp: "^NameVirtualHost"
    insertafter: "EOF"
    line: "NameVirtualHost *:{{ item.port }}"
  with_items:
    - { filename: /etc/httpd/conf/httpd.conf, port: 80 }
    - { filename: /etc/httpd/conf.d/ssl.conf, port: 443 }

- name: Make apache logs accessible to wheel group
  file:
    path: /var/log/httpd
    mode: 0750
    group: wheel

#Required for seboolean module to work
- yum:
    name: libsemanage-python
    state: installed

- name: Allow httpd to initiate network connection to tomcat
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Ensure Apache is started and enabled on boot.
  service:
    name: httpd
    state: restarted
    enabled: yes
