---

- name: Ensure apache packages are installed.
  yum: name={{ item }} state=installed
  with_items: "{{ apache_packages }}"
  register: apache_install_packages

- name: Ensure Apache is started and enabled on boot.
  service: "name=httpd state=started enabled=yes"
