- name: Fix ssl.conf _default_ vhost
  lineinfile:
    dest="/etc/httpd/conf.d/ssl.conf"
    regexp="<VirtualHost .*:443>"
    line="<VirtualHost 127.0.0.1:443>"

- name: Make apache logs accessible to wheel group
  file: path=/var/log/httpd mode=0750 group=wheel

- name: Allow httpd to initiate network connection to tomcat
  command: "/usr/sbin/setsebool -P httpd_can_network_connect 1"

- name: remove standard sites
  file: state=absent
        path=/etc/httpd/conf.d/vhosts.conf

- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/{{ domain }}.conf
  notify:
    - restart httpd
