- name: Fix ssl.conf _default_ vhost
  lineinfile:
    dest="/etc/httpd/conf.d/ssl.conf"
    regexp="<VirtualHost .*:443>"
    line="<VirtualHost 127.0.0.1:443>"

- name: Make apache logs accessible to wheel group
  file: path=/var/log/httpd mode=0750 group=wheel

- name: Allow httpd to initiate network connection to tomcat
  when: environment_name != "dev"
  command: "/usr/sbin/setsebool -P httpd_can_network_connect 1"

- name: enable connections through firewall (iptables)
  when: environment_name == "dev"
  command: iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 80
    - 443

- name: remove standard sites
  file: state=absent
        path=/etc/httpd/conf.d/vhosts.conf

- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/{{ domain }}.conf
  notify:
    - restart httpd
