kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-webapp
parameters:
  - name: APP_NAME
    required: true
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: GIT_URL
    required: true
  - name: GIT_REF
    required: true
    value: "develop"
  - name: STAGE
    required: true
    value: "test"
  - name: BUILDER_IMAGE
    required: true
    value: "s2i-war-builder:latest"
  - name: COMMON_VERSION
    value: 3.6.0.+
  - name: INFRA_VERSION
    value: 3.7.0.+
  - name: BUILD_VERSION
    required: true
    value: 1.0-OPENSHIFT
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
      resources: {}
      source:
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        contextDir: /
        type: Git
      strategy:
        sourceStrategy:
          env:
          - name: COMMON_VERSION
            value: ${COMMON_VERSION}
          - name: INFRA_VERSION
            value: ${INFRA_VERSION}
          - name: BUILD_VERSION
            value: ${BUILD_VERSION}
          - name: BUILDER_IMAGE
            value: ${BUILDER_IMAGE}
          from:
            kind: "ImageStreamTag"
            name: ${BUILDER_IMAGE}
          forcePull: true
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:${BUILD_VERSION}
      source:
        dockerfile: |-
          FROM registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift:latest
          LABEL maintainer="inera.se"
          ENV APP_NAME=${APP_NAME}

          RUN rm -rf /opt/webserver/webapps/*

          ADD http://repo1.maven.org/maven2/javax/servlet/jsp/jstl/javax.servlet.jsp.jstl-api/1.2.1/javax.servlet.jsp.jstl-api-1.2.1.jar $JWS_HOME/lib
          ADD http://repo1.maven.org/maven2/org/glassfish/web/javax.servlet.jsp.jstl/1.2.1/javax.servlet.jsp.jstl-1.2.1.jar  $JWS_HOME/lib  
          ADD http://repo1.maven.org/maven2/org/apache/activemq/activemq-client/5.13.0/activemq-client-5.13.0.jar $JWS_HOME/lib
          ADD http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar $JWS_HOME/lib
          ADD http://repo1.maven.org/maven2/org/fusesource/hawtbuf/hawtbuf/1.9/hawtbuf-1.9.jar $JWS_HOME/lib
          ADD http://repo1.maven.org/maven2/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar $JWS_HOME/lib
          ADD http://repo1.maven.org/maven2/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar $JWS_HOME/lib

          USER root
          RUN chown jboss /opt/webserver/lib/*
          RUN chmod 644 /opt/webserver/lib/*
          USER jboss 
          
          ADD ROOT.war /opt/webserver/webapps/
          ADD build.info /opt/webserver/
          ADD launch.sh /opt/webserver/bin/
        images:
          - from:
              kind: ImageStreamTag
              name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
            paths:
              - sourcePath: /tmp/artifacts/.
                destinationDir: "."
      strategy:
        type: Docker
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
