kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-webapp
parameters:
  - name: APP_NAME
    required: true
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: GIT_URL
    required: true
  - name: GIT_REF
    required: true
    value: "develop"
  - name: STAGE
    required: true
    value: "test"
  - name: BUILDER_IMAGE
    required: true
    value: "s2i-war-builder:latest"
  - name: COMMON_VERSION
    value: 3.10.0.+
  - name: INFRA_VERSION
    value: 3.10.0.+
  - name: REF_DATA_VERSION
    value: 1.0-SNAPSHOT
  - name: BUILD_VERSION
    required: true
    value: 1.0-OPENSHIFT
  - name: CONTEXT_PATH
    required: true
    value: ROOT
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
      source:
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        contextDir: /
        type: Git
      resources:
        limits:
          cpu: 2
          memory: 2304Mi
        requests:
          cpu: 200m
          memory: 2Gi
      strategy:
        sourceStrategy:
          env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: STAGE
            value: ${STAGE}
          - name: COMMON_VERSION
            value: ${COMMON_VERSION}
          - name: INFRA_VERSION
            value: ${INFRA_VERSION}
          - name: REF_DATA_VERSION
            value: ${REF_DATA_VERSION}
          - name: BUILD_VERSION
            value: ${BUILD_VERSION}
          - name: BUILDER_IMAGE
            value: ${BUILDER_IMAGE}
          - name: JAVA_TOOL_OPTIONS
            value: '-Xms512m -Xmx1536m'
          from:
            kind: "ImageStreamTag"
            name: ${BUILDER_IMAGE}
          forcePull: true
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 600
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:${BUILD_VERSION}
      source:
        dockerfile: |-
          FROM docker-registry.default.svc:5000/dintyg/tomcat-base:latest
          ENV APP_NAME=${APP_NAME}
          ADD ROOT.war $JWS_HOME/webapps/${CONTEXT_PATH}.war
          ADD build.info $JWS_HOME/
        images:
          - from:
              kind: ImageStreamTag
              name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
            paths:
              - sourcePath: /tmp/artifacts/.
                destinationDir: "."
      strategy:
        type: Docker
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}-verified
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
        
