apiVersion: v1
kind: Template
metadata:
  name: testrunnertemplate-pod
parameters:
- name: APP_NAME
  required: true
- name: STAGE
  required: true
  value: "test"
- name: TARGET_URL
  required: true
- name: JOB_NAME
  required: true
- name: BUILD_VERSION
  required: true  
- name: CALLBACK_URL
  required: true
- name: BUILD_TAG
  required: true
- name: IMAGE
  required: true
- name: TESTS
  required: true
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${BUILD_TAG}"
    labels:
      app: ${APP_NAME}
      stage: ${STAGE}
  spec:
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    containers:
      - env:
        - name: TARGET_URL
          value: ${TARGET_URL}
        - name: CALLBACK_URL
          value: ${CALLBACK_URL}
        - name: REPORT_DIR
          value: /mnt/reports/${JOB_NAME}/${BUILD_VERSION}
        - name: JAVA_OPTS
          value: "-Xmx1G"
        image: ${IMAGE}
        name: ${BUILD_TAG}
        command: [ "/usr/libexec/s2i/run", "testrun", "${TESTS}" ]
        volumeMounts:
        - mountPath: /mnt/reports
          name: rep-vol
    restartPolicy: Never
    volumes:
      - name: rep-vol
        persistentVolumeClaim:
          claimName: "test-reports"

