apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: testrunner-template
  namespace: intyg
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: 'testrunner-${BUILD_TAG}'
    spec:
      containers:
        - env:
            - name: TARGET_URL
              value: '${TARGET_URL}'
            - name: GIT_URL
              value: '${GIT_URL}'
            - name: BUILD_VERSION
              value: '${BUILD_VERSION}'
            - name: INFRA_VERSION
              value: '${INFRA_VERSION}'
            - name: CALLBACK_URL
              value: '${CALLBACK_URL}'
            - name: JOB_NAME
              value: '${JOB_NAME}'
          image: 'docker-registry.default.svc:5000/intyg/testrunner:latest'
          name: 'testrunner-${BUILD_TAG}'
          volumeMounts:
            - mountPath: /mnt/reports
              name: rep-vol
      restartPolicy: Never
      volumes:
        - claimName: test-reports
          name: rep-vol
parameters:
  - name: TARGET_URL
    required: true
  - name: GIT_URL
    required: true
  - name: COMMON_VERSION
    value: 3.7.0.+
  - name: INFRA_VERSION
    value: 3.7.0.+
  - name: BUILD_VERSION
    required: true
  - name: JOB_NAME
    required: true
  - name: CALLBACK_URL
    required: true
  - name: BUILD_TAG
    required: true
