---

- name: Install some basic dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
   - unzip
   - man
   - man-pages
   - tree

- name: Upgrade all packages
  yum:
    name: "{{item}}"
    state: latest
  with_items:
   - unzip
   - man
   - man-pages
   - tree
