apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: EriksScript
  generation: 3
  labels:
    app: mysql
    environment: test
  name: mysql
  namespace: intygstjanster-test
spec:
  replicas: 1
  selector:
    app: mysql
    deploymentconfig: mysql
  template:
    metadata:
      annotations:
        openshift.io/generated-by: EriksScript
      labels:
        app: mysql
        deploymentconfig: mysql
        environment: test
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          image: eriklupander/mysqltest
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: volume-mysql-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-mysql-1
          persistentVolumeClaim:
            claimName: mysql-storage-claim
  test: false
