apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: EriksScript
  labels:
    app: mysql
    environment: test
  name: mysql
  namespace: intygstjanster-test
spec:
  ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    deploymentconfig: mysql
  sessionAffinity: None
  type: ClusterIP
