---
# file: roles/self-signed-certificate/tasks/main.yml

- name: Make sure openssl is installed
  when: ansible_os_family == "RedHat"
  yum: name=openssl state=present

- name: Make sure openssl is installed
  when: ansible_os_family == "Debian"
  apt: name=openssl state=present

- name: create certs dir
  file: state=directory path={{ inera_root }}/certs

- name: Create self-signed certificate
  command: creates={{ inera_root }}/certs/self-signed.crt
    openssl req -batch -x509 -nodes -days 3650 -newkey rsa:2048 -keyout {{ inera_root }}/certs/self-signed.key -out {{ inera_root }}/certs/self-signed.crt
