---

#- name: Ensure MySQL Yum repo is installed
#  shell: rpm -Uvh http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
#  args:
#    creates: /etc/yum.repos.d/mysql-community.repo

- name: Ensure libselinux-python is installed.
  yum:
    name: libselinux-python
    state: present

- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mysql_packages }}"
  register: mysql_install_packages

- name: Ensure MySQL Python libraries are installed.
  yum:
    name: MySQL-python
    state: installed

- name: Ensure MySQL is started and enabled on boot.
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  when: mysql_install_packages is defined and mysql_install_packages.changed
