---
# file: roles/tomcat_priv/tasks/main.yml

- name: add group "{{ tomcat_group }}"
  group: "name={{ tomcat_user }}"

- name: add user "{{ tomcat_user }}"
  user: "name={{ tomcat_user }} group={{ tomcat_group }} createhome=no"

- name: delete home dir for symlink of tomcat
  file: "state=absent path={{ tomcat_priv_home }}"

- name: Download tomcat
  get_url: url={{ tomcat_download_url }}
           dest={{ archive_dir }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL.tar.gz

- name: make dir
  file: "state=directory path={{ inera_root }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL"

- name: Extract tomcat
  command: tar -zxf {{ archive_dir }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL.tar.gz -C {{ inera_root }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL --strip-components 1

  #unarchive: src={{ archive_dir }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL.tar.gz
  #          dest={{ inera_root }}/PRIVATLAKARPORTAL copy=no

- name: Create symlink to tomcat home
  file: state=link src={{ inera_root }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL path={{ tomcat_priv_home }} mode=755

- name: Change ownership of Tomcat installation
  file: path={{ inera_root }}/apache-tomcat-{{ tomcat_version }}-PRIVATLAKARPORTAL owner=inera-tomcat group=inera-tomcat state=directory recurse=yes


###########

- name: create log dir
  command: mv {{ tomcat_home }}/logs /var/log/{{ tomcat_priv_service }}
  args:
    creates: "/var/log/{{ tomcat_priv_service }}/"

- name: create tomcat directory in lib
  file: path=/var/lib/{{ tomcat_priv_service }} state=directory mode=0755

- name: create var directories
  command: "mv {{ tomcat_priv_home }}/{{ item }} /var/lib/{{ tomcat_priv_service }}/{{ item }}"
  args: 
    creates: "/var/lib/{{ tomcat_priv_service }}/{{ item }}"
  with_items:
    - conf
    - webapps

- name: remove installed wars
  file: state=absent
        path=/var/lib/{{ tomcat_priv_service }}/webapps/{{ item }}
  with_items:
    - examples

- name: remove installed dirs
  file: state=absent
        path={{ tomcat_priv_home }}/{{ item }}
  with_items:
    - conf
    - webapps
    - logs

- name: redirect log dir
  file: state=link 
        src=/var/log/{{ tomcat_priv_service }} 
        dest={{ tomcat_priv_home }}/logs

- name: create tomcat internal links
  file: state=link
        src=/var/lib/{{ tomcat_priv_service }}/{{ item }}
        dest={{ tomcat_priv_home }}/{{ item }}
  with_items:
    - conf
    - webapps

- name: set rights on dirs
  file: owner={{ tomcat_user }} group={{ tomcat_user }} path={{ item }} state=directory recurse=yes
  with_items:
    - /var/log/{{ tomcat_priv_service }}
    - /var/lib/{{ tomcat_priv_service }}

#####

- name: Add init.d script
  template: src=tomcat-init.sh.j2 dest=/etc/init.d/{{ tomcat_priv_service }} mode=755

- name: Add tomcat-user.xml
  template: src=tomcat-users.xml.j2 dest={{ tomcat_priv_home }}/conf/tomcat-users.xml owner={{ tomcat_user }} mode=644

- name: Add server.xml
  template: src=server.xml.j2 dest={{ tomcat_priv_home }}/conf/server.xml owner={{ tomcat_user }} mode=644

- name: Enable Tomcat
  service: name={{ tomcat_priv_service }} state=stopped enabled=yes
