apiVersion: v1
kind: Template
metadata:
  name: activemq-template
  annotations:
    description: "Description"
    iconClass: "icon-activemq"
    tags: "messagebus"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: activemq-master
  spec:
    containers:
    - env:
      - name: environment
        value: test
      image: rmohr/activemq:5.14.5-alpine
      name: activemq
      ports:
      - containerPort: 1883
        protocol: TCP
      - containerPort: 5672
        protocol: TCP
      - containerPort: 8161
        protocol: TCP
      - containerPort: 61613
        protocol: TCP
      - containerPort: 61614
        protocol: TCP
      - containerPort: 61616
        protocol: TCP
labels:
  environment: test






apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2017-10-27T14:09:20Z
    creationTimestamp: null
    generation: 2
    labels:
      app: activemq
      environment: test
    name: activemq
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: rmohr/activemq:5.14.5-alpine
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/intygstjanster-test/activemq:5.14.5-alpine
      generation: 2
      importPolicy: {}
      name: 5.14.5-alpine
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: activemq
      environment: test
    name: activemq
  spec:
    replicas: 1
    selector:
      app: activemq
      deploymentconfig: activemq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: activemq
          deploymentconfig: activemq
          environment: test
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_USERNAME
            value: admin
          - name: ACTIVEMQ_PASSWORD
            value: admin
          image: rmohr/activemq@sha256:dba6922c7931c9f9505092c8f19fe901638294540c4a14594c17fde2c5562227
          imagePullPolicy: IfNotPresent
          name: activemq
          ports:
          - containerPort: 1883
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          - containerPort: 8161
            protocol: TCP
          - containerPort: 61613
            protocol: TCP
          - containerPort: 61614
            protocol: TCP
          - containerPort: 61616
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - activemq
        from:
          kind: ImageStreamTag
          name: activemq:5.14.5-alpine
          namespace: intygstjanster-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.name: activemq-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: activemq
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: image change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"activemq","namespace":"intygstjanster-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/intygstjanster-test/deploymentconfigs/activemq","uid":"6ccee4c7-bb20-11e7-ad4e-fa5d59dae812","resourceVersion":"3222","generation":3,"creationTimestamp":"2017-10-27T14:09:19Z","labels":{"app":"activemq","environment":"test"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["activemq"],"from":{"kind":"ImageStreamTag","namespace":"intygstjanster-test","name":"activemq:5.14.5-alpine"},"lastTriggeredImage":"rmohr/activemq@sha256:dba6922c7931c9f9505092c8f19fe901638294540c4a14594c17fde2c5562227"}}],"replicas":1,"test":false,"selector":{"app":"activemq","deploymentconfig":"activemq"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"activemq","deploymentconfig":"activemq","environment":"test"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"containers":[{"name":"activemq","image":"rmohr/activemq@sha256:dba6922c7931c9f9505092c8f19fe901638294540c4a14594c17fde2c5562227","ports":[{"containerPort":1883,"protocol":"TCP"},{"containerPort":5672,"protocol":"TCP"},{"containerPort":8161,"protocol":"TCP"},{"containerPort":61613,"protocol":"TCP"},{"containerPort":61614,"protocol":"TCP"},{"containerPort":61616,"protocol":"TCP"}],"env":[{"name":"ACTIVEMQ_USERNAME","value":"admin"},{"name":"ACTIVEMQ_PASSWORD","value":"admin"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"ImageStreamTag","namespace":"intygstjanster-test","name":"activemq:5.14.5-alpine"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2017-10-27T14:09:19Z","lastTransitionTime":"2017-10-27T14:09:19Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: activemq
      environment: test
      openshift.io/deployment-config.name: activemq
    name: activemq-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: activemq
      uid: 6ccee4c7-bb20-11e7-ad4e-fa5d59dae812
  spec:
    replicas: 1
    selector:
      app: activemq
      deployment: activemq-1
      deploymentconfig: activemq
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: activemq
          openshift.io/deployment.name: activemq-1
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: activemq
          deployment: activemq-1
          deploymentconfig: activemq
          environment: test
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_USERNAME
            value: admin
          - name: ACTIVEMQ_PASSWORD
            value: admin
          image: rmohr/activemq@sha256:dba6922c7931c9f9505092c8f19fe901638294540c4a14594c17fde2c5562227
          imagePullPolicy: IfNotPresent
          name: activemq
          ports:
          - containerPort: 1883
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          - containerPort: 8161
            protocol: TCP
          - containerPort: 61613
            protocol: TCP
          - containerPort: 61614
            protocol: TCP
          - containerPort: 61616
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: activemq
      environment: test
    name: activemq
  spec:
    ports:
    - name: 1883-tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 8161-tcp
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: 61613-tcp
      port: 61613
      protocol: TCP
      targetPort: 61613
    - name: 61614-tcp
      port: 61614
      protocol: TCP
      targetPort: 61614
    - name: 61616-tcp
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      deploymentconfig: activemq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"intygstjanster-test","name":"activemq-1","uid":"6d9b2914-bb20-11e7-ad4e-fa5d59dae812","apiVersion":"v1","resourceVersion":"3238"}}
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: activemq
      openshift.io/deployment.name: activemq-1
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/scc: anyuid
    creationTimestamp: null
    generateName: activemq-1-
    labels:
      app: activemq
      deployment: activemq-1
      deploymentconfig: activemq
      environment: test
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: activemq-1
      uid: 6d9b2914-bb20-11e7-ad4e-fa5d59dae812
  spec:
    containers:
    - env:
      - name: ACTIVEMQ_USERNAME
        value: admin
      - name: ACTIVEMQ_PASSWORD
        value: admin
      image: rmohr/activemq@sha256:dba6922c7931c9f9505092c8f19fe901638294540c4a14594c17fde2c5562227
      imagePullPolicy: IfNotPresent
      name: activemq
      ports:
      - containerPort: 1883
        protocol: TCP
      - containerPort: 5672
        protocol: TCP
      - containerPort: 8161
        protocol: TCP
      - containerPort: 61613
        protocol: TCP
      - containerPort: 61614
        protocol: TCP
      - containerPort: 61616
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
          - SYS_CHROOT
        privileged: false
        seLinuxOptions:
          level: s0:c8,c2
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-xr20m
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-qjb03
    nodeName: localhost
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c8,c2
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-xr20m
      secret:
        defaultMode: 420
        secretName: default-token-xr20m
  status:
    phase: Pending
    qosClass: BestEffort
kind: List
metadata: {}
