CREATE TABLE `CERTIFICATE_METRICS` (
  `ID` varchar(255) NOT NULL,
  `CERTIFICATE_TYPE` varchar(255) NOT NULL,
  `CARE_GIVER_NAME` varchar(255) NOT NULL,
  `CARE_GIVER_ID` varchar(255) NOT NULL DEFAULT 'x',
  `CARE_UNIT_NAME` varchar(255) NOT NULL,
  `CARE_UNIT_ID` varchar(255) NOT NULL DEFAULT 'x',
  `POSTAL_NUMBER` varchar(255) NOT NULL DEFAULT 'x',
  `POSTAL_CITY` varchar(255) NOT NULL DEFAULT 'x',
  PRIMARY KEY (`ID`),
  KEY `IDX_CERTIFICATE_METRICS_ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
