---
# This playbook provisions apache 

- hosts: apache
  become: yes
  environment:
    "{{ proxy_env }}"
  vars_files:
    - vars/apache.yml
  roles:
    - self-signed-certificate
    - apache
    - apache-ports
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
