---
# This playbook provisions tomcat 

- hosts: tomcat
  sudo: yes 

  roles:
    - git
    - oracle-jre7
    - {role: tomcat7, when: "'{{inventory_hostname}}' != 'privatlakarportal-{{environment_name}}'"}
    - {role: tomcat-priv, when: "'{{inventory_hostname}}' == 'privatlakarportal-{{environment_name}}'"}
    - global-systemvariabler
