---
# This playbook provisions apache 

- hosts: apache
  sudo: yes 
  vars_files:
    - vars/apache.yml
  vars:
    apache_root: /etc/apache2
  roles:
    - self-signed-certificate
    - { role: geerlingguy.apache }
    - apache-ports
    - apache-templated-vhosts
    - apache-vhost
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

