---
# This playbook provisions tomcat 

- hosts: tomcat
  sudo: yes 

  roles:
    - git
    - oracle-jre7
    - {role: tomcat7, when: inventory_hostname != "privatlakarportal-demo"}
    - {role: tomcat-priv, when: inventory_hostname == "privatlakarportal-demo"}
    - global-systemvariabler
