apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: logsender
    name: logsender-pipeline
    template: application-template-sample-pipeline
  name: logsender-pipeline
  namespace: intygstjanster-test
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        try {
           timeout(time: 20, unit: 'MINUTES') {
              node {
                  stage('build') {
                    openshiftBuild(buildConfig: 'logsender', showBuildLogs: 'true')
                  }
                }
           }
        } catch (err) {
           echo "in catch block"
           echo "Caught: ${err}"
           currentBuild.result = 'FAILURE'
           throw err
        }
    type: JenkinsPipeline
status:
  lastVersion: 0
