apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: EriksFinaTemplate
  creationTimestamp: null
  generation: 1
  labels:
    app: intygstjanst
    environment: test
  name: intygstjanst
spec:
  replicas: 1
  selector:
    app: intygstjanst
    deploymentconfig: intygstjanst
  template:
    metadata:
      annotations:
        openshift.io/generated-by: EriksFinaTemplate
      labels:
        app: intygstjanst
        deploymentconfig: intygstjanst
        environment: test
    spec:
      containers:
      - env:
        - name: SPRING_ACTIVE_PROFILES
          value: test
        - name: INTYG_DB_USERNAME
          value: intyg
        - name: INTYG_DB_PASSWORD
          value: intyg
        - name: NTJP_URL
          value: intyg
        image: eriklupander/intygstjanst:latest
        imagePullPolicy: IfNotPresent
        name: intygstjanst
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
         - mountPath: /opt/inera/intygstjanst-konfiguration
           name: intygstjanst-konfiguration-test
           readOnly: true
         - mountPath: /opt/inera/certifikat
           name: intygstjanst-test-certifikat
           readOnly: true

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
       - configMap:
           defaultMode: 420
           name: intygstjanst-konfiguration-test
         name: intygstjanst-konfiguration-test
       - name: intygstjanst-test-certifikat
         secret:
           defaultMode: 420
           secretName: intygstjanst-test-certifikat
  test: false
