apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: intygstjanst
    template: application-template-sample-pipeline
  name: intygstjanst
  namespace: intygstjanster-test
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: '172.30.1.1:5000/intygstjanster-test/intygstjanst'
