---

- name: Add tomcat group "{{ tomcat7_group }}"
  group: "name={{ tomcat7_group }}"

- name: Add tomcat user "{{ tomcat7_user }}"
  user: "name={{ tomcat7_user }} group={{ tomcat7_group }} createhome=no"

- name: Download tomcat
  get_url: url={{ tomcat_download_url }}
           dest={{ archive_dir }}/apache-tomcat-{{ tomcat7_version }}.tar.gz

- name: Make tomcat install dir
  file: "state=directory path={{ tomcat7_install_dir}}"

- name: Extract tomcat
  unarchive:
    src: "{{ archive_dir }}/apache-tomcat-{{ tomcat7_version }}.tar.gz"
    dest: "{{ tomcat7_install_dir}}"
    extra_opts: ['--strip-components=1', '--show-stored-names']
    remote_src: yes
    creates: "{{ tomcat7_install_dir}}/bin/startup.sh"

- name: Remove tomcat home symlink, if exists
  file: "state=absent path={{ tomcat7_home }}"

- name: Create symlink to tomcat home
  file: state=link src={{ tomcat7_install_dir}} path={{ tomcat7_home }} mode=755

- name: Change ownership of tomcat installation
  file: path={{ tomcat7_install_dir}} owner={{ tomcat7_user }} group={{ tomcat7_group }} state=directory recurse=yes

###########

- name: Remove installed dirs and links
  file: state=absent
        path={{ tomcat7_home }}/{{ item }}
  with_items:
    - webapps
    - logs

- name: Create tomcat internal directories
  file: path={{ tomcat7_home }}/{{ item }} state=directory owner={{ tomcat7_user }} group={{ tomcat7_group }} recurse=yes
  with_items:
    - conf
    - webapps

- name: Create log dir
  file: path=/var/log/{{ tomcat7_service }} state=directory owner={{ tomcat7_user }} group={{ tomcat7_group }} recurse=yes

- name: Redirect log dir
  file: state=link src=/var/log/{{ tomcat7_service }} dest={{ tomcat7_home }}/logs owner={{ tomcat7_user }} group={{ tomcat7_group }}

- name: Add init.d script
  template: src=tomcat-init.sh.j2 dest=/etc/init.d/{{ tomcat7_service }} mode=755

- name: Add tomcat-user.xml
  template: src=tomcat-users.xml.j2 dest={{ tomcat7_home }}/conf/tomcat-users.xml owner={{ tomcat7_user }} mode=644

- name: Add server.xml
  template: src=server.xml.j2 dest={{ tomcat7_home }}/conf/server.xml owner={{ tomcat7_user }} mode=644

- name: Enable tomcat
  service: name={{ tomcat7_service }} state=stopped enabled=yes
