---
# file: roles/apache-vhost/tasks/main.yml

- name: Fix ssl.conf _default_ vhost
  when: ansible_os_family == "RedHat"
  lineinfile:
    dest="/etc/httpd/conf.d/ssl.conf"
    regexp="<VirtualHost .*:443>"
    line="<VirtualHost 127.0.0.1:443>"

- name: Allow httpd to initiate network connection to tomcat
  when: ansible_os_family == "RedHat"
  command: "/usr/sbin/setsebool -P httpd_can_network_connect 1"
