---

- name: "Shut down tomcat"
  service:
    name: "{{ tomcat7_service }}"
    state: stopped
    pattern: "{{ tomcat7_service }}"

- name: "Remove tomcat logs for {{ domain }}"
  file:
    path: "/var/log/{{ tomcat7_service }}"
    state: absent

- name: "Remove {{ inera_root }}/{{ inventory_hostname }}-tomcat"
  file:
    path: "{{ inera_root }}/{{ inventory_hostname }}-tomcat"
    state: absent

- name: "Remove {{ tomcat7_install_dir }}"
  file:
    path: "{{ tomcat7_install_dir }}"
    state: absent
