apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: privatlakarportal
    template: application-template-sample-pipeline
  name: privatlakarportal
  namespace: intygstjanster-test
spec:
  lookupPolicy:
    local: false
