---

- name: Create {{ inera_root }} directory
  file: state=directory dest={{ inera_root }} mode=755

- name: Create {{ archive_dir }} directory
  file: state=directory dest={{ archive_dir }} mode=755

- name: Create JAVA_HOME directory
  file: state=directory dest={{ java_home }} mode=755

- name: Download Oracle JRE
  get_url: url="http://download.oracle.com/otn-pub/java/jdk/{{ java_version }}/{{ jre_tarball }}"
           dest="{{ archive_dir }}/{{ jre_tarball }}"
           headers='Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

- name: Extract java
  unarchive:
    src: "{{ archive_dir }}/{{ jre_tarball }}"
    dest: "{{ java_home }}"
    extra_opts: ['--strip-components=1', '--show-stored-names']
    remote_src: yes
    creates: "{{ java_home }}/bin/java"

- name: Set JAVA_HOME variable
  lineinfile:
    dest="/etc/profile"
    regexp="export JAVA_HOME"
    insertafter="EOF"
    line="export JAVA_HOME={{ java_home }}"

- name: Remove unused java softlink, if exists
  file: state=absent path=/usr/local/bin/java

- name: Remove previous link, if exists
  file: state=absent path=/usr/bin/java

- name: Make java link
  file: state=link src="{{ java_home }}/bin/java" path=/usr/bin/java
